// TYPE: video, special, trailer, update
// CAST: array of cast members
// GROUP: ordered group (e.g. Bob & Mike)
// TAGS: unordered groups (e.g. Tom's House, Classic Video)
// CHANNEL: where vid was uploaded

export enum Genre {
  Video = "video",
  Special = "special",
  Trailer = "trailer",
  Update = "update",
}

export enum Group {
  BobAndMike = "Bob & Mike",
  RyansWackyWorld = "Ryan's Wacky World",
  JeremyVideoProductions = "JeremyVideoProductions",
  OsterleyField = "Osterley Field",
  AccommodationSeries = "Accommodation",
  EducationalContent = "Educational Content",
  FightScene = "Fight Scene",
  TheUnethicals = "The Unethicals",
  AntiSugarPSA = "Anti-Sugar PSA",
  TheLawSeries = "Law",
  InDepthDocumentaries = "In-Depth Documentaries",
}

export enum Tag {
  Animation = "Animation",
  BFI = "BFI",
  GMOD = "GMOD",
  MadDG = "MadD G",
  PercyHouse = "Percy's House",
  Serbia = "Serbia",
  TomHouse = "Tom's House",
  Rooftop = "Carpark Roof",
  JakeVideo = "Filmfreak",
  Documentary = "Documentary",
  WeeklyYear = "2022",
}

export enum Cast {
  Tom = "Tom",
  Aleks = "Aleks",
  Riley = "Riley",
  Jake = "Jake",
  Duja = "Duja",
  Abdi = "Abdi",
  Jaskirat = "Jaskirat",
  Blaise = "Blaise",
  Angus = "Angus",
  Johnson = "Johnson",
}

export enum Channel {
  ArgonFilms = "Argon Films",
  GyroFilms = "Gyro Films",
  BFIFamilyFilms = "BFI Family Films",
  JakeFilmFreak = "Jake Filmfreak",
  AleksanderMarkovic = "Aleksander Marković",
}

export type Video = {
  type: "video";
  id: string;
  title: string;
  length: number;
  genre: Genre;
  group?: Group;
  tags?: Tag[];
  cast?: Cast[];
  channel: Channel;
};

// TODO - cut out endcards
export const VIDEOS: Video[] = [
  {
    type: "video",
    id: "NhzkgI2tUAg",
    title: "Bob & Mike's Last Ride",
    length: 416,
    genre: Genre.Video,
    group: Group.BobAndMike,
    cast: [Cast.Tom, Cast.Aleks],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "zAw07AkDel0",
    title: "WE'RE DOING IT AGAIN",
    length: 150,
    genre: Genre.Update,
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "MKwrxh6NEg4",
    title: "ZIPWHARF (2024) - FULL TRAILER",
    length: 137,
    genre: Genre.Trailer,
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "Kgubk4mFnZs",
    title: "ZIPWHARF (2024) - Teaser Trailer",
    length: 61,
    genre: Genre.Trailer,
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "Te3i3h_7FIs",
    title: "IMPORTANT ANNOUNCEMENT",
    length: 289,
    genre: Genre.Update,
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "QNWpIUlcXKE",
    title: "Argon Films 2022",
    length: 3725,
    genre: Genre.Special,
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "pvujSmljshw",
    title: "Too Hot Sauce",
    length: 1162,
    genre: Genre.Video,
    tags: [Tag.MadDG, Tag.WeeklyYear],
    cast: [Cast.Jake],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "SZlU8qSJZsg",
    title: "The Void War",
    length: 54,
    genre: Genre.Video,
    tags: [Tag.Animation, Tag.WeeklyYear],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "-9Ky0YgclDA",
    title: "Out Of The Void He Comes",
    length: 48,
    genre: Genre.Video,
    tags: [Tag.Animation, Tag.WeeklyYear],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "LTaFVW-Z2Mc",
    title: "Philosophical Thoughts",
    length: 43,
    genre: Genre.Video,
    tags: [Tag.Animation, Tag.WeeklyYear],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "MBiKITiH5wQ",
    title: "The Funniest Joke In The World",
    length: 16,
    genre: Genre.Video,
    tags: [Tag.Animation, Tag.WeeklyYear],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "chCByc6o-h8",
    title: "Ca$h Masterz",
    length: 229,
    genre: Genre.Video,
    tags: [Tag.WeeklyYear],
    cast: [Cast.Jake],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "fEJ9YPOS9Vw",
    title: "Syon Lane",
    length: 355,
    genre: Genre.Video,
    tags: [Tag.WeeklyYear],
    cast: [Cast.Aleks],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "I8JWxkjA_fY",
    title: "Terrifying Human Baby Hybrid Caught On Camera",
    length: 124,
    genre: Genre.Video,
    tags: [Tag.WeeklyYear],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "6CLG2uFUU2E",
    title: "BOB & MIKE 3 - Regenerations",
    length: 471,
    genre: Genre.Video,
    group: Group.BobAndMike,
    tags: [Tag.WeeklyYear],
    cast: [Cast.Aleks],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "D5Z4D33GGmQ",
    title:
      "SCARIEST GMOD NEXTBOT EVER??? SCARIEST UNKNOWN CREATURE IN GMOD??? [JUMPSCARE WARNING] (Scary)",
    length: 135,
    genre: Genre.Video,
    tags: [Tag.GMOD, Tag.WeeklyYear],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "LqJQ6paC6a0",
    title: "MadD G - Imagine",
    length: 213,
    genre: Genre.Video,
    tags: [Tag.MadDG, Tag.WeeklyYear],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "9RwWJdjXeLE",
    title: "Top 7 Places in London",
    length: 159,
    genre: Genre.Video,
    tags: [Tag.Serbia, Tag.WeeklyYear],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "B6TOgXNmI7c",
    title: "How To Check if your House is Haunted",
    length: 301,
    genre: Genre.Video,
    group: Group.JeremyVideoProductions,
    tags: [Tag.WeeklyYear],
    cast: [Cast.Tom],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "TW0RhJ8ADwM",
    title: "Tiny Eminem",
    length: 163,
    genre: Genre.Video,
    tags: [Tag.WeeklyYear],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "fR5P8Q7YeDg",
    title: "MadD G - triBute 2 LiZ (R.i.P Queen)",
    length: 156,
    genre: Genre.Video,
    tags: [Tag.MadDG, Tag.WeeklyYear],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "wuWg4UVi4gI",
    title: "trying cigarettes for the first time",
    length: 135,
    genre: Genre.Video,
    tags: [Tag.Serbia, Tag.WeeklyYear],
    cast: [Cast.Jake],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "6TsEJwD4zlc",
    title: "Wizz Air",
    length: 11,
    genre: Genre.Video,
    tags: [Tag.Animation, Tag.WeeklyYear],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "vnfX23-QX-8",
    title: "THE ULTIMATE PIMP",
    length: 279,
    genre: Genre.Video,
    group: Group.OsterleyField,
    tags: [Tag.WeeklyYear],
    cast: [Cast.Abdi, Cast.Jaskirat],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "04KPRqnPEFQ",
    title: "20 GUYS",
    length: 314,
    genre: Genre.Video,
    tags: [Tag.WeeklyYear],
    cast: [Cast.Tom],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "5wym7TJMIIM",
    title: "You should jump",
    length: 165,
    genre: Genre.Video,
    tags: [Tag.WeeklyYear],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "PbEHtA304l8",
    title: "Sid Movies Presents: Watching the Truman Show for the First Time",
    length: 362,
    genre: Genre.Video,
    tags: [Tag.PercyHouse, Tag.WeeklyYear],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "-pToDboBzQU",
    title: "swamp man",
    length: 201,
    genre: Genre.Video,
    tags: [Tag.WeeklyYear],
    cast: [Cast.Tom],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "a_SY48Fca8E",
    title: "the co-worker who tells awful stories",
    length: 187,
    genre: Genre.Video,
    tags: [Tag.WeeklyYear],
    cast: [Cast.Tom, Cast.Riley, Cast.Jake],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "MsSh5MTuSiE",
    title: "What If Evangelion Was Real?",
    length: 268,
    genre: Genre.Video,
    tags: [Tag.WeeklyYear],
    cast: [Cast.Tom],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "My1IOjLStWY",
    title: "QueenAI",
    length: 212,
    genre: Genre.Video,
    tags: [Tag.PercyHouse, Tag.WeeklyYear],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "J1NNq3QrOX0",
    title: "Who's That Weird Guy Over There?",
    length: 343,
    genre: Genre.Video,
    group: Group.OsterleyField,
    tags: [Tag.WeeklyYear],
    cast: [Cast.Abdi, Cast.Jaskirat],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "A2QWcIS7VyY",
    title: "#GoneViral",
    length: 452,
    genre: Genre.Video,
    tags: [Tag.WeeklyYear],
    cast: [Cast.Duja],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "xVxJCqWtwVw",
    title:
      "VNDERVVHELMER - Scary Movies (Victim of Involuntary Technological Interface)",
    length: 57,
    genre: Genre.Video,
    tags: [Tag.PercyHouse, Tag.WeeklyYear],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "VdiEP2VILFQ",
    title: "we're out of video ideas",
    length: 155,
    genre: Genre.Video,
    tags: [Tag.PercyHouse, Tag.WeeklyYear],
    cast: [Cast.Duja],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "6DHy1ZVY070",
    title: "SCARIEST GMOD ARG EVER??????? (REAL)",
    length: 258,
    genre: Genre.Video,
    tags: [Tag.GMOD, Tag.WeeklyYear],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "_xCjZWZPov8",
    title: "PISS SHOW",
    length: 226,
    genre: Genre.Video,
    group: Group.RyansWackyWorld,
    tags: [Tag.WeeklyYear],
    cast: [Cast.Jake],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "hSlDwUIneG8",
    title: "The Visitor",
    length: 564,
    genre: Genre.Video,
    tags: [Tag.TomHouse, Tag.WeeklyYear],
    cast: [Cast.Tom, Cast.Jake],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "_FqNfxggfOw",
    title: "WHAT TO DO IF A SHADOW MAN IS FOLLOWING YOU",
    length: 224,
    genre: Genre.Video,
    group: Group.JeremyVideoProductions,
    tags: [Tag.WeeklyYear],
    cast: [Cast.Tom],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "xp2AE9x3oUc",
    title: "REHABILITATION SQUAD",
    length: 324,
    genre: Genre.Video,
    tags: [Tag.WeeklyYear],
    cast: [Cast.Aleks],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "5Ci94qE4i0g",
    title: "finding a cool rock in the woods",
    length: 287,
    genre: Genre.Video,
    group: Group.OsterleyField,
    tags: [Tag.WeeklyYear],
    cast: [Cast.Abdi, Cast.Jaskirat],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "rRkNCDgqbdo",
    title: "Looking For Cryptids",
    length: 246,
    genre: Genre.Video,
    tags: [Tag.TomHouse, Tag.WeeklyYear],
    cast: [Cast.Tom],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "uRYu1GEP754",
    title: "WELCOME TO ARGON FILMS",
    length: 180,
    genre: Genre.Special,
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "8Hv3-iHUG7s",
    title: "percy manthey: outside",
    length: 457,
    genre: Genre.Video,
    tags: [Tag.WeeklyYear],
    cast: [Cast.Tom],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "GWSD182sGcs",
    title: "RUNNING LATE | 2022 Oscars Film Competition",
    length: 2094,
    genre: Genre.Video,
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "BDN_BW-koQE",
    title: "Percy's Birthday Extravaganza",
    length: 273,
    genre: Genre.Video,
    tags: [Tag.WeeklyYear],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "pmyw8fVY_0c",
    title: "ILLUMINATI CONFIRMED - The MadD G Show",
    length: 432,
    genre: Genre.Video,
    tags: [Tag.MadDG, Tag.Documentary, Tag.WeeklyYear],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "EdifJyTOpMk",
    title: "The Three Jakes",
    length: 852,
    genre: Genre.Video,
    tags: [Tag.WeeklyYear],
    cast: [Cast.Jake, Cast.Aleks],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "GeR5qRu-R1Q",
    title: "MadD G - The Inside Story",
    length: 820,
    genre: Genre.Video,
    tags: [Tag.MadDG, Tag.WeeklyYear],
    cast: [Cast.Aleks],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "gHOHP3aXnWM",
    title: "AMATEUR LABS - Interview With Map Creator",
    length: 295,
    genre: Genre.Video,
    tags: [Tag.PercyHouse, Tag.WeeklyYear],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "ybE2PPPRruY",
    title: "STOP THE WAR - MadD G",
    length: 94,
    genre: Genre.Video,
    tags: [Tag.MadDG, Tag.WeeklyYear],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "q442cF7mMiM",
    title: "Anti-Sugar PSA - 5th Anniversary Edition",
    length: 513,
    genre: Genre.Video,
    group: Group.AntiSugarPSA,
    tags: [Tag.WeeklyYear],
    cast: [Cast.Abdi, Cast.Jaskirat],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "cyPSOT53RHs",
    title: "Poop Show",
    length: 236,
    genre: Genre.Video,
    group: Group.RyansWackyWorld,
    tags: [Tag.PercyHouse, Tag.WeeklyYear],
    cast: [Cast.Jake],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "2TEQkQpzK04",
    title: "SwaggyWhiteBoy",
    length: 199,
    genre: Genre.Video,
    tags: [Tag.WeeklyYear],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "prV-LL-dWkY",
    title: "The Bunny",
    length: 117,
    genre: Genre.Video,
    tags: [Tag.WeeklyYear],
    cast: [Cast.Duja],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "zxzl6P3Rdw0",
    title: "Seinfeld Lore",
    length: 366,
    genre: Genre.Video,
    tags: [Tag.WeeklyYear],
    cast: [Cast.Jake],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "wDSA9gZjBWs",
    title: "The Slob",
    length: 269,
    genre: Genre.Video,
    tags: [Tag.TomHouse, Tag.WeeklyYear],
    cast: [Cast.Jake],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "IbRNGNDqVcI",
    title: "RAP SNACKS",
    length: 363,
    genre: Genre.Video,
    tags: [Tag.WeeklyYear],
    cast: [Cast.Jake, Cast.Duja],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "k1YssBA4MtU",
    title: "Antipsychosis",
    length: 147,
    genre: Genre.Video,
    tags: [Tag.Animation],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "cgw2etw2Ysk",
    title: "Percy Manthey's The Unethicals",
    length: 2053,
    genre: Genre.Video,
    group: Group.TheUnethicals,
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "TMoGFctnCms",
    title: "Every Kill/Death in Argon Films (as of 24/03/21)",
    length: 386,
    genre: Genre.Special,
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "YR7XQ2Lhn4w",
    title: "A Gift For Penelope",
    length: 542,
    genre: Genre.Video,
    cast: [Cast.Aleks, Cast.Blaise],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "mZWOv9E4vls",
    title: "MadD MaNiFESto",
    length: 128,
    genre: Genre.Video,
    tags: [Tag.MadDG],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "6UB7eNvENFI",
    title: "Every Teen Movie Opening",
    length: 241,
    genre: Genre.Video,
    cast: [Cast.Aleks],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "uawg7MAD3gA",
    title: "The Bread Man: The Depraved Adventures of Bob & Mike, Part II",
    length: 260,
    genre: Genre.Video,
    group: Group.BobAndMike,
    cast: [Cast.Aleks, Cast.Blaise],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "L5-A__dkgKM",
    title: "The Car: The Depraved Adventures of Bob & Mike, Part I",
    length: 377,
    genre: Genre.Video,
    group: Group.BobAndMike,
    cast: [Cast.Aleks, Cast.Blaise],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "wDx5TYQWsqc",
    title: "What the Heck is a Participatory Documentary?",
    length: 342,
    genre: Genre.Video,
    tags: [Tag.Rooftop],
    cast: [Cast.Jake, Cast.Aleks],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "MDk94MlYpSM",
    title: "THE TRUTH ABOUT 5G - The MadD G Show",
    length: 647,
    genre: Genre.Video,
    tags: [Tag.MadDG],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "itWurrJ-Klc",
    title: "ATTACK OF THE NAZI NAZIS",
    length: 240,
    genre: Genre.Video,
    cast: [Cast.Blaise, Cast.Aleks, Cast.Jake],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "-CZ3040l2mk",
    title: "Isolative",
    length: 421,
    genre: Genre.Video,
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "o7jnS_NH3fg",
    title: "[LOST VIDEO] How To Avoid Morbid Obesity",
    length: 219,
    genre: Genre.Video,
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "CPKOPic-GLI",
    title: "A Sketch That Does Not Contain The Final Accommodation",
    length: 312,
    genre: Genre.Video,
    group: Group.AccommodationSeries,
    cast: [Cast.Tom, Cast.Riley],
    channel: Channel.GyroFilms,
  },
  {
    type: "video",
    id: "fkirWoHf7r0",
    title: "FINAL ACCOMMODATION'S LAW",
    length: 436,
    genre: Genre.Video,
    group: Group.TheLawSeries,
    tags: [Tag.Rooftop],
    cast: [Cast.Tom, Cast.Riley],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "BYaydkjjHbc",
    title: "PO'S LAW",
    length: 249,
    genre: Genre.Video,
    group: Group.TheLawSeries,
    tags: [Tag.Rooftop],
    cast: [Cast.Aleks],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "gfobuKtxllA",
    title: "MURPHY'S LAW",
    length: 235,
    genre: Genre.Video,
    group: Group.TheLawSeries,
    cast: [Cast.Jake, Cast.Blaise, Cast.Abdi, Cast.Jaskirat],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "s7Z_qrA6fKA",
    title: "Toy Story 5",
    length: 164,
    genre: Genre.Video,
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "FT4apOM8yUU",
    title: "Top 50 Most Awesome Breaking Bad Facts You Didn't Know",
    length: 133,
    genre: Genre.Video,
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "uBuTW49B_Zc",
    title: "Vaccines & Violence - An In-depth Documentary",
    length: 369,
    genre: Genre.Video,
    group: Group.InDepthDocumentaries,
    cast: [Cast.Abdi],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "opQ0VKLAYdg",
    title: "Is Chicken Even Real? - An In-Depth Documentary",
    length: 452,
    genre: Genre.Video,
    group: Group.InDepthDocumentaries,
    cast: [Cast.Abdi],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "I3fJmOtakp4",
    title: "Inception 9: Jerry Seinfeld Yiffs the Planet",
    length: 211,
    genre: Genre.Video,
    group: Group.AccommodationSeries,
    tags: [Tag.BFI],
    cast: [Cast.Tom, Cast.Jake, Cast.Angus],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "ALlkw-8CMqU",
    title: "Family Guy Intro (HD)",
    length: 239,
    genre: Genre.Video,
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "J7di-a5eso4",
    title: "The House of the Future",
    length: 199,
    genre: Genre.Video,
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "zFAjhOKS6LA",
    title:
      "reactors react to reactionists reactioning to reactionors playing the chrome dino game - REACTION",
    length: 54,
    genre: Genre.Video,
    tags: [Tag.BFI],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "01Rw2f-qy1M",
    title: "A Legal Message from MadD G",
    length: 212,
    genre: Genre.Video,
    tags: [Tag.MadDG],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "kF-dT9dsudQ",
    title: "Scariest Video Ever?",
    length: 196,
    genre: Genre.Video,
    group: Group.AccommodationSeries,
    tags: [Tag.BFI],
    cast: [Cast.Johnson],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "czm5KnE4Ccw",
    title: "Secrets of the Cheese Grater | A Spiritual Journey",
    length: 346,
    genre: Genre.Video,
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "qX07QHTCUZ0",
    title:
      "the return of the revenge of the fall of the curse of the ghost | a czechslovakian art film",
    length: 127,
    genre: Genre.Video,
    group: Group.AccommodationSeries,
    tags: [Tag.BFI],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "e3ZMU8rNpVE",
    title: "How To Stop Diseases",
    length: 223,
    genre: Genre.Video,
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "UHsc8ikg33o",
    title: "Anti-Sugar PSA",
    length: 197,
    genre: Genre.Video,
    group: Group.AntiSugarPSA,
    cast: [Cast.Abdi, Cast.Jaskirat],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "MjZOLHgMl_w",
    title: "The Passage - Official Trailer",
    length: 26,
    genre: Genre.Video,
    tags: [Tag.BFI],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "rY20DPpQvzY",
    title: "[GMOD] Energy Sources Guide",
    length: 256,
    genre: Genre.Video,
    group: Group.EducationalContent,
    tags: [Tag.GMOD],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "UaZw6oTmsw0",
    title: "Physics Revision Resource",
    length: 213,
    genre: Genre.Video,
    group: Group.EducationalContent,
    tags: [Tag.GMOD],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "EIuW5YNmtQA",
    title: "Brutal Fight Scene",
    length: 215,
    genre: Genre.Video,
    group: Group.FightScene,
    cast: [Cast.Angus],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "cToieWTKGNk",
    title: "Underground Fight",
    length: 126,
    genre: Genre.Video,
    group: Group.FightScene,
    cast: [Cast.Angus],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "Z-9WavpxLbE",
    title: "Rooftop Fight",
    length: 129,
    genre: Genre.Video,
    group: Group.FightScene,
    cast: [Cast.Angus],
    channel: Channel.ArgonFilms,
  },
  {
    type: "video",
    id: "M_hcemMrsvs",
    title:
      "HEISTWARS: PATTERSON RISES | The Greatest Challenge Yet (Feat: Eric Roberts)",
    length: 2860,
    genre: Genre.Video,
    channel: Channel.GyroFilms,
  },
  {
    type: "video",
    id: "6Ar5XfCA_H4",
    title: "IMPORTANT ANOUNCEMENT",
    length: 52,
    genre: Genre.Update,
    channel: Channel.GyroFilms,
  },
  {
    type: "video",
    id: "AsvA6Wzkoxw",
    title: "HEISTWARS: THE RESCUE | Sweets, Surveillance, and Stupidity",
    length: 1959,
    genre: Genre.Video,
    channel: Channel.GyroFilms,
  },
  {
    type: "video",
    id: "YzAQwxhMluM",
    title: "HEISTWARS: REDUX | New Target, New Teams, New Rules...",
    length: 2440,
    genre: Genre.Video,
    channel: Channel.GyroFilms,
  },
  {
    type: "video",
    id: "qcORfqlcjFY",
    title: "HEISTWARS | Simulation-Based Game Show",
    length: 1632,
    genre: Genre.Video,
    channel: Channel.GyroFilms,
  },
  {
    type: "video",
    id: "6n0UVlYlQ1c",
    title: "HEISTWARS | Trailer (Experimental Game Show)",
    length: 74,
    genre: Genre.Trailer,
    channel: Channel.GyroFilms,
  },
  {
    type: "video",
    id: "vus7tOATvjg",
    title: "SPLICED | Short found-footage film",
    length: 821,
    genre: Genre.Video,
    cast: [Cast.Aleks, Cast.Tom],
    channel: Channel.GyroFilms,
  },
  {
    type: "video",
    id: "tkEslxHHSfA",
    title: "THE WITNESS | Linear version",
    length: 461,
    genre: Genre.Video,
    cast: [Cast.Tom, Cast.Blaise, Cast.Aleks],
    channel: Channel.GyroFilms,
  },
  {
    type: "video",
    id: "vmrLapxoeag",
    title: "THE WITNESS | Short mystery-thriller film",
    length: 712,
    genre: Genre.Video,
    cast: [Cast.Tom, Cast.Blaise, Cast.Aleks],
    channel: Channel.GyroFilms,
  },
  {
    type: "video",
    id: "zYYqwoxmnkg",
    title: "The Final Accommodation - Trailer",
    length: 88,
    genre: Genre.Trailer,
    channel: Channel.GyroFilms,
  },
  {
    type: "video",
    id: "UjGqf_coU_U",
    title: "THE UNETHICALS | Behind The Scenes",
    length: 476,
    genre: Genre.Video,
    group: Group.TheUnethicals,
    tags: [Tag.TomHouse, Tag.Documentary],
    cast: [Cast.Tom, Cast.Jake, Cast.Aleks],
    channel: Channel.GyroFilms,
  },
  {
    type: "video",
    id: "afBR-UHN4hk",
    title: "THE UNETHICALS | Short Action-Comedy Film",
    length: 2053,
    genre: Genre.Video,
    group: Group.TheUnethicals,
    channel: Channel.GyroFilms,
  },
  {
    type: "video",
    id: "hNYqeHSXAnQ",
    title: "THE UNETHICALS | Trailer",
    length: 113,
    genre: Genre.Trailer,
    channel: Channel.GyroFilms,
  },
  {
    type: "video",
    id: "lXIacRj9ssw",
    title: "A video which is exactly two minutes long",
    length: 167,
    genre: Genre.Video,
    tags: [Tag.BFI],
    cast: [Cast.Johnson],
    channel: Channel.GyroFilms,
  },
  {
    type: "video",
    id: "1Kt1n8VkomU",
    title: "A sketch that does not contain the letter Z",
    length: 182,
    genre: Genre.Video,
    tags: [Tag.BFI],
    cast: [Cast.Angus, Cast.Tom],
    channel: Channel.GyroFilms,
  },
  {
    type: "video",
    id: "Y8pKMBZkfBo",
    title: "THE UNETHICALS | Concept trailer",
    length: 151,
    genre: Genre.Trailer,
    tags: [Tag.BFI],
    cast: [Cast.Jake, Cast.Johnson],
    channel: Channel.GyroFilms,
  },
  {
    type: "video",
    id: "TqKg8RAD8sU",
    title: "Temporary accommodation",
    length: 336,
    genre: Genre.Video,
    group: Group.AccommodationSeries,
    tags: [Tag.BFI],
    channel: Channel.GyroFilms,
  },
  {
    type: "video",
    id: "aVVHC_u9xcw",
    title: "Macbeth on a Budget: A Tale of Disappointment",
    length: 70,
    tags: [Tag.BFI],
    genre: Genre.Video,
    channel: Channel.BFIFamilyFilms,
  },
  {
    type: "video",
    id: "pwS2DgaBvuw",
    title: "NOVA BLANC",
    length: 301,
    tags: [Tag.BFI],
    genre: Genre.Video,
    cast: [Cast.Tom, Cast.Jake],
    channel: Channel.BFIFamilyFilms,
  },
  {
    type: "video",
    id: "Xh463JCdFZI",
    title: "CANOLI AND CORRUPTION",
    length: 325,
    tags: [Tag.BFI],
    genre: Genre.Video,
    cast: [Cast.Tom],
    channel: Channel.BFIFamilyFilms,
  },
  {
    type: "video",
    id: "_eT5EcqZPyA",
    title: "CHAIRS",
    length: 249,
    tags: [Tag.BFI],
    genre: Genre.Video,
    cast: [Cast.Tom, Cast.Jake],
    channel: Channel.BFIFamilyFilms,
  },
  {
    type: "video",
    id: "SHSxW-gQo_s",
    title: "Hamlet Action",
    length: 183,
    tags: [Tag.BFI],
    genre: Genre.Video,
    cast: [],
    channel: Channel.BFIFamilyFilms,
  },
  {
    type: "video",
    id: "FvG3rIry7zY",
    title: "a TEAM - AN ACTION FILM!",
    length: 1401,
    tags: [Tag.BFI],
    genre: Genre.Video,
    channel: Channel.BFIFamilyFilms,
  },
  {
    type: "video",
    id: "Su1X1l2olm0",
    title: "DEAD FRIENDSHIP",
    length: 230,
    genre: Genre.Video,
    tags: [Tag.BFI],
    channel: Channel.BFIFamilyFilms,
  },
  {
    type: "video",
    id: "RuVGmph5nYA",
    title: "Rookie",
    length: 256,
    genre: Genre.Video,
    cast: [Cast.Aleks],
    tags: [Tag.Rooftop],
    channel: Channel.JakeFilmFreak,
  },
  {
    type: "video",
    id: "AurJgX1R4ZI",
    title: "The Outbreak (2021 Restoration)",
    length: 173,
    genre: Genre.Video,
    tags: [Tag.JakeVideo],
    cast: [Cast.Tom],
    channel: Channel.JakeFilmFreak,
  },
  {
    type: "video",
    id: "jkllvh1pOJM",
    title:
      "Cambridge Film Studies professor explains the hidden metaphors behind Robocop (1987)",
    length: 69,
    genre: Genre.Video,
    tags: [Tag.JakeVideo],
    channel: Channel.JakeFilmFreak,
  },
  {
    type: "video",
    id: "9XVdAlIr2TM",
    title: "BFI Family films exposé",
    length: 405,
    genre: Genre.Video,
    tags: [Tag.JakeVideo, Tag.Documentary],
    cast: [Cast.Tom, Cast.Riley],
    channel: Channel.JakeFilmFreak,
  },
  {
    type: "video",
    id: "1zID1KnU-OQ",
    title: "Licenziato!",
    length: 181,
    genre: Genre.Video,
    tags: [Tag.JakeVideo],
    cast: [Cast.Aleks],
    channel: Channel.JakeFilmFreak,
  },
  {
    type: "video",
    id: "_0o-qyzBUws",
    title: "The Discussion - A Blaise Jones Film",
    length: 291,
    genre: Genre.Video,
    cast: [Cast.Blaise, Cast.Aleks],
    channel: Channel.AleksanderMarkovic,
  },
];

export type Ident = {
  type: "ident";
  id: string;
  length: number;
  avoid?: string[];
  promote?: string;
};

export const IDENTS: Ident[] = [
  {
    // Ego Death
    type: "ident",
    id: "_2S_kGOtD5w",
    length: 10,
    avoid: ["Kgubk4mFnZs", "MKwrxh6NEg4"],
  },
  {
    // Surreal
    type: "ident",
    id: "JG-dGY8UfzE",
    length: 10,
    avoid: ["I3fJmOtakp4", "MjZOLHgMl_w", "wDSA9gZjBWs", "I8JWxkjA_fY"],
  },
];
