// TYPE: video, special, trailer, update
// CAST: array of cast members
// GROUP: ordered group (e.g. Bob & Mike)
// TAGS: unordered groups (e.g. Tom's House, Classic Video)
// CHANNEL: where vid was uploaded
export var VideoType;
(function (VideoType) {
    VideoType["Video"] = "video";
    VideoType["Special"] = "special";
    VideoType["Trailer"] = "trailer";
    VideoType["Update"] = "update";
})(VideoType || (VideoType = {}));
export var VideoGroup;
(function (VideoGroup) {
    VideoGroup["BobAndMike"] = "Bob & Mike";
    VideoGroup["GMOD"] = "GMOD";
    VideoGroup["RyansWackyWorld"] = "Ryan's Wacky World";
    VideoGroup["JeremyVideoProductions"] = "JeremyVideoProductions";
    VideoGroup["OsterleyField"] = "Osterley Field";
    VideoGroup["AccommodationSeries"] = "Accommodation Series";
    VideoGroup["EducationalContent"] = "Educational Content";
    VideoGroup["FightScene"] = "Fight Scene";
    VideoGroup["TheUnethicals"] = "The Unethicals";
    VideoGroup["AntiSugarPSA"] = "Anti-Sugar PSA";
    VideoGroup["TheLawSeries"] = "The Law Series";
    VideoGroup["InDepthDocumentaries"] = "In-Depth Documentaries";
})(VideoGroup || (VideoGroup = {}));
export var VideoTag;
(function (VideoTag) {
    VideoTag["Animation"] = "Animation";
    VideoTag["BFI"] = "BFI";
    VideoTag["GMOD"] = "GMOD";
    VideoTag["MadDG"] = "MadD G";
    VideoTag["PercyHouse"] = "Percy's House";
    VideoTag["Serbia"] = "Serbia";
    VideoTag["TomHouse"] = "Tom's House";
    VideoTag["Rooftop"] = "Rooftop";
})(VideoTag || (VideoTag = {}));
export const VIDEOS = [
    {
        id: "NhzkgI2tUAg",
        title: "Bob & Mike's Last Ride",
        length: 416,
        type: VideoType.Video,
        group: VideoGroup.BobAndMike,
        channel: "Argon Films",
    },
    {
        id: "zAw07AkDel0",
        title: "WE'RE DOING IT AGAIN",
        length: 150,
        type: VideoType.Update,
        channel: "Argon Films",
    },
    {
        id: "MKwrxh6NEg4",
        title: "ZIPWHARF (2024) - FULL TRAILER",
        length: 137,
        type: VideoType.Trailer,
        channel: "Argon Films",
    },
    {
        id: "Kgubk4mFnZs",
        title: "ZIPWHARF (2024) - Teaser Trailer",
        length: 61,
        type: VideoType.Trailer,
        channel: "Argon Films",
    },
    {
        id: "Te3i3h_7FIs",
        title: "IMPORTANT ANNOUNCEMENT",
        length: 289,
        type: VideoType.Update,
        channel: "Argon Films",
    },
    {
        id: "QNWpIUlcXKE",
        title: "Argon Films 2022",
        length: 3725,
        type: VideoType.Special,
        channel: "Argon Films",
    },
    {
        id: "pvujSmljshw",
        title: "Too Hot Sauce",
        length: 1162,
        type: VideoType.Video,
        tags: [VideoTag.MadDG],
        channel: "Argon Films",
    },
    {
        id: "SZlU8qSJZsg",
        title: "The Void War",
        length: 54,
        type: VideoType.Video,
        tags: [VideoTag.Animation],
        channel: "Argon Films",
    },
    {
        id: "-9Ky0YgclDA",
        title: "Out Of The Void He Comes",
        length: 48,
        type: VideoType.Video,
        tags: [VideoTag.Animation],
        channel: "Argon Films",
    },
    {
        id: "LTaFVW-Z2Mc",
        title: "Philosophical Thoughts",
        length: 43,
        type: VideoType.Video,
        tags: [VideoTag.Animation],
        channel: "Argon Films",
    },
    {
        id: "MBiKITiH5wQ",
        title: "The Funniest Joke In The World",
        length: 16,
        type: VideoType.Video,
        tags: [VideoTag.Animation],
        channel: "Argon Films",
    },
    {
        id: "chCByc6o-h8",
        title: "Ca$h Masterz",
        length: 229,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "fEJ9YPOS9Vw",
        title: "Syon Lane",
        length: 355,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "I8JWxkjA_fY",
        title: "Terrifying Human Baby Hybrid Caught On Camera",
        length: 124,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "6CLG2uFUU2E",
        title: "BOB & MIKE 3 - Regenerations",
        length: 471,
        type: VideoType.Video,
        group: VideoGroup.BobAndMike,
        channel: "Argon Films",
    },
    {
        id: "D5Z4D33GGmQ",
        title: "SCARIEST GMOD NEXTBOT EVER??? SCARIEST UNKNOWN CREATURE IN...",
        length: 135,
        type: VideoType.Video,
        group: VideoGroup.GMOD,
        channel: "Argon Films",
    },
    {
        id: "LqJQ6paC6a0",
        title: "MadD G - Imagine",
        length: 213,
        type: VideoType.Video,
        tags: [VideoTag.MadDG],
        channel: "Argon Films",
    },
    {
        id: "9RwWJdjXeLE",
        title: "Top 7 Places in London",
        length: 159,
        type: VideoType.Video,
        tags: [VideoTag.Serbia],
        channel: "Argon Films",
    },
    {
        id: "B6TOgXNmI7c",
        title: "How To Check if your House is Haunted",
        length: 301,
        type: VideoType.Video,
        group: VideoGroup.JeremyVideoProductions,
        channel: "Argon Films",
    },
    {
        id: "TW0RhJ8ADwM",
        title: "Tiny Eminem",
        length: 163,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "fR5P8Q7YeDg",
        title: "MadD G - triBute 2 LiZ (R.i.P Queen)",
        length: 156,
        type: VideoType.Video,
        tags: [VideoTag.MadDG],
        channel: "Argon Films",
    },
    {
        id: "wuWg4UVi4gI",
        title: "trying cigarettes for the first time",
        length: 135,
        type: VideoType.Video,
        tags: [VideoTag.Serbia],
        channel: "Argon Films",
    },
    {
        id: "6TsEJwD4zlc",
        title: "Wizz Air",
        length: 11,
        type: VideoType.Video,
        tags: [VideoTag.Animation],
        channel: "Argon Films",
    },
    {
        id: "vnfX23-QX-8",
        title: "THE ULTIMATE PIMP",
        length: 279,
        type: VideoType.Video,
        group: VideoGroup.OsterleyField,
        channel: "Argon Films",
    },
    {
        id: "04KPRqnPEFQ",
        title: "20 GUYS",
        length: 314,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "5wym7TJMIIM",
        title: "You should jump",
        length: 165,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "PbEHtA304l8",
        title: "Sid Movies Presents: Watching the Truman Show for the First Time",
        length: 362,
        type: VideoType.Video,
        tags: [VideoTag.PercyHouse],
        channel: "Argon Films",
    },
    {
        id: "-pToDboBzQU",
        title: "swamp man",
        length: 201,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "a_SY48Fca8E",
        title: "the co-worker who tells awful stories",
        length: 187,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "MsSh5MTuSiE",
        title: "What If Evangelion Was Real?",
        length: 268,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "My1IOjLStWY",
        title: "QueenAI",
        length: 212,
        type: VideoType.Video,
        tags: [VideoTag.PercyHouse],
        channel: "Argon Films",
    },
    {
        id: "J1NNq3QrOX0",
        title: "Who's That Weird Guy Over There?",
        length: 343,
        type: VideoType.Video,
        group: VideoGroup.OsterleyField,
        channel: "Argon Films",
    },
    {
        id: "A2QWcIS7VyY",
        title: "#GoneViral",
        length: 452,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "xVxJCqWtwVw",
        title: "VNDERVVHELMER - Scary Movies (Victim of Involuntary Technological Interface)",
        length: 57,
        type: VideoType.Video,
        tags: [VideoTag.PercyHouse],
        channel: "Argon Films",
    },
    {
        id: "VdiEP2VILFQ",
        title: "we're out of video ideas",
        length: 155,
        type: VideoType.Video,
        tags: [VideoTag.PercyHouse],
        channel: "Argon Films",
    },
    {
        id: "6DHy1ZVY070",
        title: "SCARIEST GMOD ARG EVER??????? (REAL)",
        length: 258,
        type: VideoType.Video,
        tags: [VideoTag.GMOD],
        channel: "Argon Films",
    },
    {
        id: "_xCjZWZPov8",
        title: "PISS SHOW",
        length: 226,
        type: VideoType.Video,
        group: VideoGroup.RyansWackyWorld,
        channel: "Argon Films",
    },
    {
        id: "hSlDwUIneG8",
        title: "The Visitor",
        length: 564,
        type: VideoType.Video,
        tags: [VideoTag.TomHouse],
        channel: "Argon Films",
    },
    {
        id: "_FqNfxggfOw",
        title: "WHAT TO DO IF A SHADOW MAN IS FOLLOWING YOU",
        length: 224,
        type: VideoType.Video,
        group: VideoGroup.JeremyVideoProductions,
        channel: "Argon Films",
    },
    {
        id: "xp2AE9x3oUc",
        title: "REHABILITATION SQUAD",
        length: 324,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "5Ci94qE4i0g",
        title: "finding a cool rock in the woods",
        length: 287,
        type: VideoType.Video,
        group: VideoGroup.OsterleyField,
        channel: "Argon Films",
    },
    {
        id: "rRkNCDgqbdo",
        title: "Looking For Cryptids",
        length: 246,
        type: VideoType.Video,
        tags: [VideoTag.TomHouse],
        channel: "Argon Films",
    },
    {
        id: "uRYu1GEP754",
        title: "WELCOME TO ARGON FILMS",
        length: 180,
        type: VideoType.Special,
        channel: "Argon Films",
    },
    {
        id: "8Hv3-iHUG7s",
        title: "percy manthey: outside",
        length: 457,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "GWSD182sGcs",
        title: "RUNNING LATE | 2022 Oscars Film Competition",
        length: 2094,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "BDN_BW-koQE",
        title: "Percy's Birthday Extravaganza",
        length: 273,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "pmyw8fVY_0c",
        title: "ILLUMINATI CONFIRMED - The MadD G Show",
        length: 432,
        type: VideoType.Video,
        tags: [VideoTag.MadDG],
        channel: "Argon Films",
    },
    {
        id: "EdifJyTOpMk",
        title: "The Three Jakes",
        length: 852,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "GeR5qRu-R1Q",
        title: "MadD G - The Inside Story",
        length: 820,
        type: VideoType.Video,
        tags: [VideoTag.MadDG],
        channel: "Argon Films",
    },
    {
        id: "gHOHP3aXnWM",
        title: "AMATEUR LABS - Interview With Map Creator",
        length: 295,
        type: VideoType.Video,
        tags: [VideoTag.PercyHouse],
        channel: "Argon Films",
    },
    {
        id: "ybE2PPPRruY",
        title: "STOP THE WAR - MadD G",
        length: 94,
        type: VideoType.Video,
        tags: [VideoTag.MadDG],
        channel: "Argon Films",
    },
    {
        id: "q442cF7mMiM",
        title: "Anti-Sugar PSA - 5th Anniversary Edition",
        length: 513,
        type: VideoType.Video,
        group: VideoGroup.AntiSugarPSA,
        channel: "Argon Films",
    },
    {
        id: "cyPSOT53RHs",
        title: "Poop Show",
        length: 236,
        type: VideoType.Video,
        group: VideoGroup.RyansWackyWorld,
        tags: [VideoTag.PercyHouse],
        channel: "Argon Films",
    },
    {
        id: "2TEQkQpzK04",
        title: "SwaggyWhiteBoy",
        length: 199,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "prV-LL-dWkY",
        title: "The Bunny",
        length: 117,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "zxzl6P3Rdw0",
        title: "Seinfeld Lore",
        length: 366,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "wDSA9gZjBWs",
        title: "The Slob",
        length: 269,
        type: VideoType.Video,
        tags: [VideoTag.TomHouse],
        channel: "Argon Films",
    },
    {
        id: "IbRNGNDqVcI",
        title: "RAP SNACKS",
        length: 363,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "k1YssBA4MtU",
        title: "Antipsychosis",
        length: 147,
        type: VideoType.Video,
        tags: [VideoTag.Animation],
        channel: "Argon Films",
    },
    {
        id: "cgw2etw2Ysk",
        title: "Percy Manthey's The Unethicals",
        length: 2053,
        type: VideoType.Video,
        group: VideoGroup.TheUnethicals,
        channel: "Argon Films",
    },
    {
        id: "TMoGFctnCms",
        title: "Every Kill/Death in Argon Films (as of 24/03/21)",
        length: 386,
        type: VideoType.Special,
        channel: "Argon Films",
    },
    {
        id: "YR7XQ2Lhn4w",
        title: "A Gift For Penelope",
        length: 542,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "mZWOv9E4vls",
        title: "MadD MaNiFESto",
        length: 128,
        type: VideoType.Video,
        tags: [VideoTag.MadDG],
        channel: "Argon Films",
    },
    {
        id: "6UB7eNvENFI",
        title: "Every Teen Movie Opening",
        length: 241,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "uawg7MAD3gA",
        title: "The Bread Man: The Depraved Adventures of Bob & Mike, Part II",
        length: 260,
        type: VideoType.Video,
        group: VideoGroup.BobAndMike,
        channel: "Argon Films",
    },
    {
        id: "L5-A__dkgKM",
        title: "The Car: The Depraved Adventures of Bob & Mike, Part I",
        length: 377,
        type: VideoType.Video,
        group: VideoGroup.BobAndMike,
        channel: "Argon Films",
    },
    {
        id: "wDx5TYQWsqc",
        title: "What the Heck is a Participatory Documentary?",
        length: 342,
        type: VideoType.Video,
        tags: [VideoTag.Rooftop],
        channel: "Argon Films",
    },
    {
        id: "MDk94MlYpSM",
        title: "THE TRUTH ABOUT 5G - The MadD G Show",
        length: 647,
        type: VideoType.Video,
        tags: [VideoTag.MadDG],
        channel: "Argon Films",
    },
    {
        id: "itWurrJ-Klc",
        title: "ATTACK OF THE NAZI NAZIS",
        length: 240,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "-CZ3040l2mk",
        title: "Isolative",
        length: 421,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "o7jnS_NH3fg",
        title: "[LOST VIDEO] How To Avoid Morbid Obesity",
        length: 219,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "fkirWoHf7r0",
        title: "FINAL ACCOMMODATION'S LAW",
        length: 436,
        type: VideoType.Video,
        group: VideoGroup.TheLawSeries,
        tags: [VideoTag.Rooftop],
        channel: "Argon Films",
    },
    {
        id: "BYaydkjjHbc",
        title: "PO'S LAW",
        length: 249,
        type: VideoType.Video,
        group: VideoGroup.TheLawSeries,
        tags: [VideoTag.Rooftop],
        channel: "Argon Films",
    },
    {
        id: "gfobuKtxllA",
        title: "MURPHY'S LAW",
        length: 235,
        type: VideoType.Video,
        group: VideoGroup.TheLawSeries,
        channel: "Argon Films",
    },
    {
        id: "s7Z_qrA6fKA",
        title: "Toy Story 5",
        length: 164,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "FT4apOM8yUU",
        title: "Top 50 Most Awesome Breaking Bad Facts You Didn't Know",
        length: 133,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "uBuTW49B_Zc",
        title: "Vaccines & Violence - An In-depth Documentary",
        length: 369,
        type: VideoType.Video,
        group: VideoGroup.InDepthDocumentaries,
        channel: "Argon Films",
    },
    {
        id: "opQ0VKLAYdg",
        title: "Is Chicken Even Real? - An In-Depth Documentary",
        length: 452,
        type: VideoType.Video,
        group: VideoGroup.InDepthDocumentaries,
        channel: "Argon Films",
    },
    {
        id: "I3fJmOtakp4",
        title: "Inception 9: Jerry Seinfeld Yiffs the Planet",
        length: 211,
        type: VideoType.Video,
        group: VideoGroup.AccommodationSeries,
        tags: [VideoTag.BFI],
        channel: "Argon Films",
    },
    {
        id: "ALlkw-8CMqU",
        title: "Family Guy Intro (HD)",
        length: 239,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "J7di-a5eso4",
        title: "The House of the Future",
        length: 199,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "zFAjhOKS6LA",
        title: "reactors react to reactionists reactioning to reactionors playing the chrome dino game ...",
        length: 54,
        type: VideoType.Video,
        tags: [VideoTag.BFI],
        channel: "Argon Films",
    },
    {
        id: "01Rw2f-qy1M",
        title: "A Legal Message from MadD G",
        length: 212,
        type: VideoType.Video,
        tags: [VideoTag.MadDG],
        channel: "Argon Films",
    },
    {
        id: "kF-dT9dsudQ",
        title: "Scariest Video Ever?",
        length: 196,
        type: VideoType.Video,
        group: VideoGroup.AccommodationSeries,
        tags: [VideoTag.BFI],
        channel: "Argon Films",
    },
    {
        id: "czm5KnE4Ccw",
        title: "Secrets of the Cheese Grater | A Spiritual Journey",
        length: 346,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "qX07QHTCUZ0",
        title: "the return of the revenge of the fall of the curse of the ghost | a czechslovakian art film",
        length: 127,
        type: VideoType.Video,
        group: VideoGroup.AccommodationSeries,
        tags: [VideoTag.BFI],
        channel: "Argon Films",
    },
    {
        id: "e3ZMU8rNpVE",
        title: "How To Stop Diseases",
        length: 223,
        type: VideoType.Video,
        channel: "Argon Films",
    },
    {
        id: "UHsc8ikg33o",
        title: "Anti-Sugar PSA",
        length: 197,
        type: VideoType.Video,
        group: VideoGroup.AntiSugarPSA,
        channel: "Argon Films",
    },
    {
        id: "MjZOLHgMl_w",
        title: "The Passage - Official Trailer",
        length: 26,
        type: VideoType.Video,
        tags: [VideoTag.BFI],
        channel: "Argon Films",
    },
    {
        id: "rY20DPpQvzY",
        title: "[GMOD] Energy Sources Guide",
        length: 256,
        type: VideoType.Video,
        group: VideoGroup.EducationalContent,
        tags: [VideoTag.GMOD],
        channel: "Argon Films",
    },
    {
        id: "UaZw6oTmsw0",
        title: "Physics Revision Resource",
        length: 213,
        type: VideoType.Video,
        group: VideoGroup.EducationalContent,
        tags: [VideoTag.GMOD],
        channel: "Argon Films",
    },
    {
        id: "EIuW5YNmtQA",
        title: "Brutal Fight Scene",
        length: 215,
        type: VideoType.Video,
        group: VideoGroup.FightScene,
        channel: "Argon Films",
    },
    {
        id: "cToieWTKGNk",
        title: "Underground Fight",
        length: 126,
        type: VideoType.Video,
        group: VideoGroup.FightScene,
        channel: "Argon Films",
    },
    {
        id: "Z-9WavpxLbE",
        title: "Rooftop Fight",
        length: 129,
        type: VideoType.Video,
        group: VideoGroup.FightScene,
        channel: "Argon Films",
    },
];
